version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    resource_class: medium+
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm install
      - run: npm run test:all -- --collectCoverage
      - codecov/upload:
          file: coverage/clover.xml
