name: Run tests

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - run: npm ci
      - run: npm run test:all -- --collectCoverage
      - name: Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          fail_ci_if_error: true
